# yaml-language-server: $schema=https://raw.githubusercontent.com/goreleaser/goreleaser/refs/heads/main/www/docs/static/schema.json
version: 2
project_name: azure-postgres-auth-proxy
builds:
  - env: [CGO_ENABLED=0]
    binary: azure-postgres-auth-proxy
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
- image_templates: ["ghcr.io/telenornorway/azure-postgres-auth-proxy:{{ .Version }}"]
  build_flag_templates:
  - --label=org.opencontainers.image.title={{ .ProjectName }}
  - --label=org.opencontainers.image.url=https://github.com/TelenorNorway/azure-postgres-auth-proxy
  - --label=org.opencontainers.image.source=https://github.com/TelenorNorway/azure-postgres-auth-proxy
  - --label=org.opencontainers.image.version={{ .Version }}
  - --label=org.opencontainers.image.created={{ .Date }}
  - --label=org.opencontainers.image.revision={{ .FullCommit }}
  - --label=org.opencontainers.image.licenses=Apache-2.0
  extra_files:
    - dist